cvm : bug fix for undefined reference to 'virtcca_cvm_allowed' while compiling.
Fixes a linking error due to an undefined reference to
'virtcca_cvm_allowed' when KVM is not enabled.

Signed-off-by: liupingwei <liupingwei0317@outlook.com>